services:
  db_postgres:
    container_name: postgres-oauth2
    image: postgres:14-alpine3.21
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgres/data
  cache_redis:
    image: redis:8.0.2-alpine
    container_name: redis-oauth2
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379
    volumes: 
      - ./tmp/redis:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
  cloudflared:
    image: cloudflare/cloudflared@sha256:f9d5c5b94cd7337c0c939a6dbf5537db34030828c243fca6b589fd85ab25d43b
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    volumes:
      - ./cloudflared:/etc/cloudflared
volumes:
  cache:
    driver: local