basePath: /v1
definitions:
  github_com_johnquangdev_oauth2_repository_models.User:
    properties:
      avatar:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      provider:
        description: e.g. "google"
        type: string
      provider_id:
        description: unique user ID from provider
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  model.JwtResponse:
    properties:
      accessToken:
        type: string
      expiresAtAccessToken:
        type: string
      expiresAtRefreshToken:
        type: string
      refreshToken:
        type: string
    type: object
  model.User:
    properties:
      gmail:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      picture:
        type: string
      provider:
        type: string
      provider_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Backend oauth2 Golang Clean Architecture
  title: oauth2 Golang Clean Architecture
  version: "1.0"
paths:
  /v1/auth/google/callback:
    get:
      consumes:
      - application/json
      description: Callback and create user or allow user login
      parameters:
      - description: token từ Google
        in: body
        name: token
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.JwtResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Google Callback
      tags:
      - OAuth2
  /v1/auth/google/login:
    get:
      consumes:
      - application/json
      description: Trả về URL để redirect người dùng đến trang đăng nhập của Google
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Google Login
      tags:
      - OAuth2
  /v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Thoát phiên làm việc của người dùng
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Logout người dùng
      tags:
      - Auth
  /v1/auth/profile:
    get:
      consumes:
      - application/json
      description: Trả về thông tin người dùng đã xác thực qua Bearer Token (JWT)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_johnquangdev_oauth2_repository_models.User'
        "401":
          description: Unauthorized – Token không hợp lệ hoặc hết hạn
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Lỗi hệ thống
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Lấy thông tin người dùng
      tags:
      - Auth
  /v1/auth/register:
    post:
      consumes:
      - application/json
      description: Tạo tài khoản người dùng trong hệ thống
      parameters:
      - description: Thông tin người dùng
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Đăng ký người dùng mới
      tags:
      - Auth
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
